/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
static yyconst short int yy_accept[355] =
    {   0,
        0,    0,   96,   94,   92,   91,   80,   94,   94,   80,
       80,   94,   71,   80,   80,   71,   80,   71,   80,   82,
       82,   80,   80,   80,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       94,   92,   77,    0,   87,    0,   78,    0,   93,   86,
        8,   72,   73,   83,    6,    7,   83,   88,   88,   88,
       82,   74,   76,   75,   85,   90,   85,   85,   85,   85,
       85,   85,   85,   17,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   18,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   79,   87,
        0,    0,   83,    0,   83,    0,   84,   88,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   15,   85,   85,   85,   85,   85,
       85,   85,   85,   10,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,    0,   81,   81,    0,
       84,   89,   84,   89,   12,   85,   28,   13,   85,   85,
       85,   85,   85,   19,   85,   85,   32,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,

       63,   65,   14,   85,   85,   66,   68,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       25,   85,   85,    9,   85,   85,   85,    0,   81,   81,
       22,   85,   24,   85,   85,   85,   26,   85,   85,   85,
       59,   85,   60,   36,   85,   61,   62,   37,   85,   85,
       39,   85,   41,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   57,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   16,    0,   85,   85,   85,
       11,   30,   33,   34,   85,   85,   85,   56,   85,   42,
       85,   70,   51,   85,   43,   44,   21,   45,   46,   85,

       85,   58,   27,   20,   85,   49,   69,   85,   85,   85,
        0,   85,   85,   29,   35,   50,   38,   40,   64,   67,
       47,   52,   48,   85,   54,   85,    5,    5,   31,   23,
       53,   55,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    3,    0,
        1,    4,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   11,   11,   20,
       21,   22,    1,   23,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       11,    1,   11,    1,   26,    1,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   24,   36,   37,   38,   39,
       40,   41,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   11,   48,   11,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[49] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    3,    4,    1,    5,    5,    1,
        1,    1,    6,    5,    5,    6,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1
    } ;

static yyconst short int yy_base[363] =
    {   0,
        0,    0,  712,  713,   47,  713,  690,  704,  668,  713,
      699,   44,  713,  690,  693,  713,  690,   34,   43,   40,
       45,  683,  682,  681,  678,   39,   46,   44,   45,   64,
       43,   62,   54,   67,   69,   87,   79,   49,   92,   55,
      652,  118,  713,  693,  713,  656,  713,  687,  686,  713,
      713,  713,  713,  120,  713,  713,  124,  128,  679,  139,
      144,  713,  713,  713,  671,  670,  125,   96,   80,  102,
      133,  127,  138,  144,  145,  148,  149,  150,  154,  151,
      153,  155,  156,  170,  173,  160,  161,  669,  175,  180,
      183,   91,  184,  185,  114,  186,  189,  187,  191,  192,

      195,  190,  188,  197,  199,  203,  214,  216,  713,  713,
      664,  162,  225,  234,  241,  243,  249,  256,  217,  219,
      247,  235,  253,  240,  258,  259,  263,  250,  256,  265,
      266,  267,  269,  268,  667,  272,  275,  277,  278,  279,
      283,  280,  293,  666,  288,  286,  225,  295,  291,  303,
      298,  304,  306,  309,  311,  317,  312,  310,  319,  318,
      325,  324,  329,  327,  330,  337,  655,  345,  349,  358,
      351,  365,  363,  367,  664,  352,  663,  662,  356,  364,
      366,  367,  368,  661,  369,  370,  660,  371,  372,  373,
      380,  381,  394,  376,  384,  387,  386,  395,  398,  401,

      404,  659,  658,  406,  405,  407,  657,  408,  409,  410,
      411,  416,  417,  428,  419,  420,  432,  434,  430,  437,
      656,  443,  444,  655,  445,  446,  447,  639,  455,  464,
      653,  454,  652,  449,  452,  463,  651,  467,  453,  468,
      650,  469,  649,  648,  470,  647,  646,  645,  473,  474,
      644,  476,  643,  477,  478,  480,  487,  484,  489,  490,
      492,  494,  642,  495,  500,  502,  503,  505,  506,  507,
      509,  510,  511,  513,  514,  641,  636,  518,  519,  515,
      639,  638,  637,  636,  520,  529,  528,  635,  525,  634,
      531,  633,  632,  532,  631,  630,  629,  628,  627,  533,

      539,  626,  625,  624,  535,  623,  622,  546,  547,  549,
      640,  552,  553,  620,  619,  618,  617,  616,  615,  614,
      613,  612,  611,  554,  610,  555,  713,  537,  609,  608,
      607,  606,  588,  587,  581,  589,  582,  592,  589,  576,
      581,  587,  584,  543,  404,  550,  553,  365,  713,   81,
      713,  713,  713,  713,  594,  600,  603,  604,  608,  611,
       52,  616
    } ;

static yyconst short int yy_def[363] =
    {   0,
      354,    1,  354,  354,  354,  354,  354,  355,  354,  354,
      354,  356,  354,  354,  354,  354,  354,  354,  354,  357,
      357,  354,  354,  354,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      354,  354,  354,  355,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  357,  357,  359,
      357,  354,  354,  354,  358,  354,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  354,  354,
      354,  354,  354,  360,  354,  361,  357,  359,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  354,  354,  354,  360,
      354,  360,  354,  361,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  354,  354,  354,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  354,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      362,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  354,  354,  358,  358,
      358,  358,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354,  354
    } ;

static yyconst short int yy_nxt[762] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,    4,   25,   25,   25,   25,   26,   27,   28,
       29,   30,   31,   25,   32,   25,   25,   25,   33,   25,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   49,
       42,   54,   54,   50,   55,   57,  174,   58,   58,   56,
       57,   66,   61,   61,   60,   66,   66,   66,   66,   60,
       60,   66,   69,   87,   73,   60,   66,   66,   67,   70,
       68,   75,   71,   74,   66,   72,   66,  103,  108,   66,
       76,   66,   77,   88,   78,   79,   80,   91,   90,   94,

       89,   66,   66,   81,   82,   83,   84,   85,   92,   66,
       86,   93,  353,   66,   66,   95,  101,   96,   66,   42,
      102,   42,  121,  104,   66,  147,  120,   97,  122,   98,
       99,  105,  106,  100,  107,  112,   66,  113,  113,  112,
      153,  115,  115,   57,  114,   58,   58,   66,  114,   66,
      114,  116,   60,  116,  114,   66,  117,  117,   60,   57,
       66,   61,   61,  123,  119,  124,   66,   66,   60,  125,
       66,   66,   66,   66,   60,   66,   66,   66,   66,  168,
      168,  133,   66,   66,  128,  129,  138,  127,  126,  130,
      132,  131,   66,  134,  135,   66,  136,   66,  139,  137,

      140,  142,   66,  141,  143,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,  156,  145,   66,  144,   66,
      161,   66,  149,  150,  146,   66,  158,  148,  151,  154,
      155,  152,  157,  163,  160,  159,   66,  162,   66,   66,
      169,   66,  113,  113,  164,  176,  170,   66,  170,  114,
      166,  171,  171,  175,  165,  114,  169,   66,  115,  115,
      173,  173,   66,  205,  354,  114,  117,  117,  354,   66,
      354,  114,   66,   59,   59,   66,  178,  177,   66,  179,
       66,   66,  180,  181,  182,   66,  183,   66,   66,   66,
       66,   66,  185,  184,   66,  186,  187,   66,  191,   66,

       66,   66,   66,  194,  196,   66,  192,  188,   66,  197,
       66,  189,  190,   66,  200,   66,  195,   66,  193,  199,
       66,  201,  198,  206,  203,   66,   66,  204,   66,  209,
      208,   66,   66,   66,   66,  202,  213,  207,  211,   66,
       66,   66,  210,  216,  212,  215,   66,   66,  221,   66,
      219,   66,   66,  218,  214,  222,  217,  220,  224,   66,
      112,  225,  229,  229,  112,  223,  230,  230,  171,  171,
      354,  226,  354,  227,   66,  171,  171,  354,   66,  354,
      173,  173,  354,  354,  354,  354,   66,  231,   66,   66,
       66,   66,   66,   66,   66,   66,  352,  232,   66,  237,

      234,  241,   66,   66,  236,  248,   66,  233,   66,   66,
      239,  235,  238,  242,  240,  243,   66,   66,  244,  245,
       66,  251,  246,   66,  249,  250,   66,   66,   66,   66,
       66,   66,   66,   66,  253,  252,  247,  255,   66,   66,
      258,   66,   66,  347,  254,  256,  260,  263,  257,  262,
       66,  261,   66,  259,   66,  265,   66,  266,  267,   66,
      268,  264,  269,  271,  270,   66,   66,   66,   66,   66,
      169,   66,  229,  229,   66,   66,   66,  276,  273,  169,
      275,  230,  230,  274,  278,   66,  272,  279,  280,   66,
       66,   66,   66,  281,  283,   66,   66,  282,   66,   66,

       66,  284,   66,  287,  291,  288,   66,  290,  285,   66,
      294,   66,   66,  286,   66,  289,   66,   66,  293,  295,
      296,  292,   66,  298,   66,   66,  299,   66,   66,   66,
      297,   66,   66,   66,  302,   66,   66,   66,  307,  304,
       66,   66,   66,  305,  300,  301,  306,   66,  303,  308,
       66,   66,  310,   66,   66,   66,  309,   66,  314,  312,
      316,   66,  315,  313,  321,  323,  317,  318,   66,   66,
      322,   66,  319,  320,   66,   66,   66,   66,  325,  333,
      334,  348,  346,  330,  350,  331,  332,  345,  349,  324,
      344,  351,  326,  329,   44,   44,   44,   44,   44,   44,

       48,   48,   48,   48,   48,   48,   59,   59,   65,   65,
      118,  343,  118,  172,  342,  172,  327,  341,  327,  327,
      327,  327,  340,  339,  338,  337,  336,  335,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,  328,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,  311,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,  277,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,  228,   66,   66,
      167,   66,   66,   66,  354,   50,   50,  111,  110,  109,

       66,   64,   63,   62,   53,   52,   51,   47,   46,   45,
       43,  354,    3,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354
    } ;

static yyconst short int yy_chk[762] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,   12,
        5,   18,   18,   12,   19,   20,  361,   20,   20,   19,
       21,   26,   21,   21,   20,   31,   28,   29,   27,   21,
       20,   38,   27,   31,   28,   21,   33,   40,   26,   27,
       26,   29,   27,   28,   32,   27,   30,   38,   40,   34,
       30,   35,   30,   32,   30,   30,   30,   34,   33,   35,

       32,   37,   69,   30,   30,   30,   30,   30,   34,   36,
       30,   34,  350,   92,   39,   36,   37,   36,   68,   42,
       37,   42,   69,   39,   70,   92,   68,   36,   70,   36,
       36,   39,   39,   36,   39,   54,   95,   54,   54,   57,
       95,   57,   57,   58,   54,   58,   58,   67,   57,   72,
       54,   60,   58,   60,   57,   71,   60,   60,   58,   61,
       73,   61,   61,   71,   67,   72,   74,   75,   61,   73,
       76,   77,   78,   80,   61,   81,   79,   82,   83,  112,
      112,   80,   86,   87,   76,   77,   83,   75,   74,   78,
       79,   78,   84,   81,   81,   85,   82,   89,   84,   82,

       84,   86,   90,   85,   87,   91,   93,   94,   96,   98,
      103,   97,  102,   99,  100,   98,   90,  101,   89,  104,
      103,  105,   94,   94,   91,  106,  100,   93,   94,   96,
       97,   94,   99,  105,  102,  101,  107,  104,  108,  119,
      113,  120,  113,  113,  106,  120,  114,  147,  114,  113,
      108,  114,  114,  119,  107,  113,  115,  122,  115,  115,
      116,  116,  124,  147,  117,  115,  117,  117,  118,  121,
      118,  115,  128,  118,  118,  123,  122,  121,  129,  123,
      125,  126,  124,  124,  125,  127,  126,  130,  131,  132,
      134,  133,  128,  127,  136,  129,  130,  137,  134,  138,

      139,  140,  142,  138,  139,  141,  136,  131,  146,  140,
      145,  132,  133,  149,  142,  143,  138,  148,  137,  141,
      151,  143,  140,  148,  145,  150,  152,  146,  153,  150,
      149,  154,  158,  155,  157,  143,  154,  148,  152,  156,
      160,  159,  151,  156,  153,  155,  162,  161,  160,  164,
      159,  163,  165,  158,  154,  161,  157,  159,  163,  166,
      168,  164,  168,  168,  169,  162,  169,  169,  171,  171,
      170,  165,  170,  166,  176,  170,  170,  172,  179,  172,
      173,  173,  172,  172,  174,  174,  180,  176,  181,  182,
      183,  185,  186,  188,  189,  190,  348,  179,  194,  185,

      181,  190,  191,  192,  183,  194,  195,  180,  197,  196,
      188,  182,  186,  190,  189,  190,  193,  198,  191,  192,
      199,  197,  193,  200,  195,  196,  201,  205,  204,  206,
      208,  209,  210,  211,  199,  198,  193,  201,  212,  213,
      206,  215,  216,  345,  200,  204,  209,  212,  205,  211,
      214,  210,  219,  208,  217,  214,  218,  215,  216,  220,
      217,  213,  218,  220,  219,  222,  223,  225,  226,  227,
      229,  234,  229,  229,  235,  239,  232,  227,  223,  230,
      226,  230,  230,  225,  232,  236,  222,  234,  235,  238,
      240,  242,  245,  236,  239,  249,  250,  238,  252,  254,

      255,  240,  256,  249,  255,  250,  258,  254,  242,  257,
      258,  259,  260,  245,  261,  252,  262,  264,  257,  259,
      260,  256,  265,  262,  266,  267,  264,  268,  269,  270,
      261,  271,  272,  273,  267,  274,  275,  280,  272,  269,
      278,  279,  285,  270,  265,  266,  271,  289,  268,  273,
      287,  286,  275,  291,  294,  300,  274,  305,  280,  278,
      286,  301,  285,  279,  300,  305,  287,  289,  308,  309,
      301,  310,  291,  294,  312,  313,  324,  326,  309,  328,
      328,  346,  344,  313,  347,  324,  326,  343,  346,  308,
      342,  347,  310,  312,  355,  355,  355,  355,  355,  355,

      356,  356,  356,  356,  356,  356,  357,  357,  358,  358,
      359,  341,  359,  360,  340,  360,  362,  339,  362,  362,
      362,  362,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  325,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  314,  311,  307,  306,  304,  303,  302,  299,
      298,  297,  296,  295,  293,  292,  290,  288,  284,  283,
      282,  281,  277,  276,  263,  253,  251,  248,  247,  246,
      244,  243,  241,  237,  233,  231,  228,  224,  221,  207,
      203,  202,  187,  184,  178,  177,  175,  167,  144,  135,
      111,   88,   66,   65,   59,   49,   48,   46,   44,   41,

       25,   24,   23,   22,   17,   15,   14,   11,    9,    8,
        7,    3,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
#line 2 "scanner.l"
  #include <stdio.h>
  #include <string.h>

  // Type of tokens.
  typedef enum {key, id, op, punc, integer, doub, ch, sci, str, nl, noth, error} Type;
  typedef enum {false, true} bool; // Boolean algebra.

  void print(Type type); // Print out the output messages.

  int numLines = 0; // Count the number of lines of the input file.
  char line[1000] = ""; // Buffer for the texts of a line.
  bool inComment = false; // See if the current position is in a comment.
  bool mulComment = false; // See which type of comment.
  bool inError = false; // See if encounter error.
  bool sourceOn = true; // Control pragma source on or off.
  bool tokenOn = true; // Control pragma token on or off.
#line 666 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 30 "scanner.l"

#line 819 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 355 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 713 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "scanner.l"
{sourceOn = true;
                     print(noth);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "scanner.l"
{sourceOn = false;
                      print(noth);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 35 "scanner.l"
{tokenOn = true;
                    print(noth);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "scanner.l"
{tokenOn = false;
                     print(noth);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "scanner.l"
{print(error);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "scanner.l"
{inComment = true;
      mulComment = true;
      print(noth);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "scanner.l"
{inComment = true;
      mulComment = false;
      print(noth);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "scanner.l"
{inComment = false;
      mulComment = false;
      print(noth);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 49 "scanner.l"
{print(key);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "scanner.l"
{print(key);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "scanner.l"
{print(key);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "scanner.l"
{print(key);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "scanner.l"
{print(key);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "scanner.l"
{print(key);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "scanner.l"
{print(key);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "scanner.l"
{print(key);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "scanner.l"
{print(key);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "scanner.l"
{print(key);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "scanner.l"
{print(key);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "scanner.l"
{print(key);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "scanner.l"
{print(key);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "scanner.l"
{print(key);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "scanner.l"
{print(key);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "scanner.l"
{print(key);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "scanner.l"
{print(key);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "scanner.l"
{print(key);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "scanner.l"
{print(key);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "scanner.l"
{print(key);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "scanner.l"
{print(key);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "scanner.l"
{print(key);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "scanner.l"
{print(key);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "scanner.l"
{print(key);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "scanner.l"
{print(key);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "scanner.l"
{print(key);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "scanner.l"
{print(key);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "scanner.l"
{print(key);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "scanner.l"
{print(key);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "scanner.l"
{print(key);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "scanner.l"
{print(key);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "scanner.l"
{print(key);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "scanner.l"
{print(key);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "scanner.l"
{print(key);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "scanner.l"
{print(key);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "scanner.l"
{print(key);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "scanner.l"
{print(key);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "scanner.l"
{print(key);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "scanner.l"
{print(key);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "scanner.l"
{print(key);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "scanner.l"
{print(key);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "scanner.l"
{print(key);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "scanner.l"
{print(key);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "scanner.l"
{print(key);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "scanner.l"
{print(key);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "scanner.l"
{print(key);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "scanner.l"
{print(key);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "scanner.l"
{print(key);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "scanner.l"
{print(key);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "scanner.l"
{print(key);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "scanner.l"
{print(key);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "scanner.l"
{print(key);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "scanner.l"
{print(key);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "scanner.l"
{print(key);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "scanner.l"
{print(key);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "scanner.l"
{print(key);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "scanner.l"
{print(key);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "scanner.l"
{print(key);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "scanner.l"
{print(key);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "scanner.l"
{print(key);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "scanner.l"
{print(key);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "scanner.l"
{print(key);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "scanner.l"
{print(punc);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 112 "scanner.l"
{print(op);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 "scanner.l"
{print(op);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 "scanner.l"
{print(op);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 115 "scanner.l"
{print(op);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 116 "scanner.l"
{print(op);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "scanner.l"
{print(op);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "scanner.l"
{print(op);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "scanner.l"
{print(op);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "scanner.l"
{print(op);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 121 "scanner.l"
{print(error);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 122 "scanner.l"
{print(integer);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 123 "scanner.l"
{print(doub);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 124 "scanner.l"
{print(sci);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 125 "scanner.l"
{print(id);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 126 "scanner.l"
{print(ch);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 127 "scanner.l"
{print(str);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 128 "scanner.l"
{print(error);}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 129 "scanner.l"
{print(error);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "scanner.l"
{print(error);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "scanner.l"
{inComment = (mulComment == true) ? true : false;
    mulComment = (inComment == 1) ? true : false;
    print(nl);
    strcpy(line, "");}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 135 "scanner.l"
{print(noth);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 136 "scanner.l"
{print(noth);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "scanner.l"
{print(error);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 138 "scanner.l"
ECHO;
	YY_BREAK
#line 1390 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 355 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 355 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 354);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 138 "scanner.l"

int main(int argc, char **argv)
{
  yyin = fopen(argv[1], "r"); // Input file
  yylex();
  return 0;
}
int yywrap()
{
  return 1; // EOF
}
void print(Type type)
{
  switch(type)
  {
    case key:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#key:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case id:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#id:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case op:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#op:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case punc:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#punc:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case integer:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#integer:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case doub:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#double:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case ch:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#char:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case sci:
      if (inComment == false && inError == false && tokenOn == true)
      {
        printf("#sci:%s\n", yytext);
      }
      strcat(line, yytext);
      break;
    case str:
      if (inComment == false && inError == false && tokenOn == true)
      {
        char printStr[1000];
        strncpy(printStr, yytext + 1, yyleng - 2);
        printStr[yyleng - 2] = '\0';
        printf("#string:%s\n", printStr);
      }
      strcat(line, yytext);
      break;
    case nl:
      if (inError == false && sourceOn == true)
      {
        printf("%d:%s\n", ++numLines, line);
        break;
      }
      else if (inError == false && sourceOn == false)
      {
        ++numLines;
        break;
      }
      else if (inError == true)
      {
        fprintf(stderr, "Error at line %d: %s\n", ++numLines, line);
        exit(1);
      }
      else
      {
        break;
      }
    case noth:
      strcat(line, yytext);
      break;
    case error:
      if (inComment == true)
      {
        break;
      }
      else
      {
        if (inError == false)
        {
          inError = true;
          strcpy(line, yytext);
        }
        else
        {
          strcat(line, yytext);
        }
      }
  }
}